<?php
namespace MCloudResources\Controller;

use MCloudResources\Controller\AppController;

/**
 * OwnedResources Controller
 *
 * @property \MCloudResources\Model\Table\OwnedResourcesTable $OwnedResources
 */
class OwnedResourcesController extends AbstractOwnedResourcesController
{

    public function isAuthorized($user) : bool
    {
        // Allow all users to list, view and add projects
        if (in_array($this->request->getParam('action'), ['view', 'add', 'index', 'dashboard'])){
            if (isset($user['role']) && $user['role'] === 'user') {
                return true;
            }
        }

        if (in_array($this->request->getParam('action'), ['edit', 'delete'])){
            $id = $this->request->getParam('pass.0');
            if ($this->OwnedResources->isOwnedBy($id, $user['id'])) {
                return true;
            }
        }

        return parent::isAuthorized($user); // TODO: Change the autogenerated stub
    }

    /**
     * Index method
     *
     * @return \Cake\Network\Response|null
     */
    public function dashboard()
    {
        $ownedResources = $this->OwnedResources->find()->contain([
            'ResourceGroups', 'ResourceClasses', 'Users'
        ])->limit(10);

        $this->set(compact('ownedResources'));
        $this->set('_serialize', ['ownedResources']);
    }

}
