image: registry.cakehub.sk/cakehub/cakeapp:fpm

# Environment variables setting
.default-variables: &default-variables
    MYSQL_ROOT_PASSWORD: cak3appd4tabase
    MYSQL_PASSWORD: cak3appd4tabase
    MYSQL_DATABASE: cakeapp
    REDIS_SERVER: redis
    REDIS_SERVER_PORT: 6379

# For Postgres DB
.postgres-variables: &postgres-variables
    variables:
        <<: *default-variables
        MYSQL_DB_NAME: cakeapp
        MYSQL_USER: postgres
        MYSQL_HOST: postgres
        MYSQL_PORT: 5432
        POSTGRES_PASSWORD: cak3appd4tabase
        POSTGRES_DB: cakeapp

# For MariaDB
.mariadb-variables: &mariadb-variables
    variables:
        <<: *default-variables
        MYSQL_DB_TEST_NAME: cakeapp
        MYSQL_USER: cakeapp
        MYSQL_HOST: mariadb
        MYSQL_PORT: 3306

# Cache vendor directory
.default-cache: &default-cache
    key: "cake-app-with-php-7"
    paths:
        - vendor/

# push cache
.push-cache: &push-cache
    cache:
        <<: *default-cache
        policy: push

# pull cache
.pull-cache: &pull-cache
    cache:
        <<: *default-cache
        policy: pull

stages:
    - prepare
    - build
    - test
    - post-test
    - deploy

# Install all dependencies
.install-dependencies: &install-dependencies
    - composer -V
    - composer install
    - chmod a+x bin/cake

# PHP Lint script using CakePHP coding standards
.php-lint: &php-lint
    - composer require cakephp/cakephp-codesniffer:dev-master
    - chmod +x vendor/bin/phpcs
    - vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests ./config ./plugins

# CodeCanyon Application Setup
# Remove all unnecessary folders
.clean-folders: &clean-folders
    - rm -rf .git
    - rm -rf ./tmp
    - rm -rf ./logs

.run-on-do-docker: &run-on-do-docker
    tags:
        - digitalocean
        - docker

# Prepare Section
# -----------------------------------
setup-cakeapp:
    <<: *push-cache
    stage: prepare
    script: *install-dependencies
    <<: *run-on-do-docker

# Post-Test section
# -----------------------------------

# Lint
php lint:
    <<: *pull-cache
    stage: post-test
    environment:
        name: staging
        url: https://helix.maymeow.tokyo/MayMeowCloudPlatform/maymeow-cloud
    before_script: *install-dependencies
    script: *php-lint
    allow_failure: true
    <<: *run-on-do-docker

# Test section
# -----------------------------------

# PHP Unit test
php:mariadb-phpunit:
    <<: *pull-cache
    <<: *mariadb-variables
    stage: test
    services:
        - redis
        - mariadb
    stage: test
    before_script: *install-dependencies
    script:
        # - bin/cake mcloud_setup
        - phpunit --coverage-text --colors=never
    <<: *run-on-do-docker

db:postgres-setup-script:
    <<: *pull-cache
    <<: *postgres-variables
    stage: test
    services:
        - postgres
        - redis
    before_script: *install-dependencies
    script:
        - bin/cake plugin loaded
        - bin/cake mcloud_setup
        - bin/cake cake_app_migrations status
    <<: *run-on-do-docker

db:postgres-migrations:
    <<: *pull-cache
    <<: *postgres-variables
    stage: test
    services:
        - postgres
        - redis
    before_script: *install-dependencies
    script:
        - bin/cake migrations migrate -p CakeAuth
        - bin/cake migrations rollback -p CakeAuth
    <<: *run-on-do-docker

# Build section
# -----------------------------------
docker:build-master:
    image: docker:latest
    services:
       - docker:dind
    stage: build
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    script: *clean-folders
    after_script:
        - cp docker-compose.default.yml docker-compose.yml
        - docker build --pull -t "$CI_REGISTRY_IMAGE" .
        - docker push "$CI_REGISTRY_IMAGE"
    <<: *run-on-do-docker
    only:
        - master

docker:build-tags:
    image: docker:latest
    services:
       - docker:dind
    stage: build
    environment:
        name: production
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    script: *clean-folders
    after_script:
        - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
        - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    <<: *run-on-do-docker
    only:
        - tags

# Deploy Section
# -----------------------------------

# Deploy for Manual setup from source code only when tags are set up
publish artifacts:
    <<: *pull-cache
    stage: deploy
    environment:
        name: production
    before_script: *install-dependencies
    script: *clean-folders
    only:
        - tags
    <<: *run-on-do-docker
    artifacts:
        name: "cakeapp-ce-${CI_COMMIT_TAG}"
        paths:
            - .
        expire_in: 7 days

# Publishing for github
publish to gitlab:
    image: registry.cakehub.sk/cakeci/github-deploy:latest
    stage: deploy
    environment:
        name: staging
    only:
        - github-master
    script:
        - git@github.com:CakeAppSK/cakeapp-ce.git github-master
    <<: *run-on-do-docker
    when: manual
