image: registry.cakehub.sk/cakehub/cakeapp:cli

variables:
    MYSQL_ROOT_PASSWORD: MayMeowCloud2017
    MYSQL_DATABASE: maylab
    MYSQL_USER: MayMeowCloud2017
    MYSQL_PASSWORD: MayMeowCloud2017
    MYSQL_HOST: mariadb
    MYSQL_PORT: 3306
    # Setting for testing database
    MYSQL_DB_TEST_NAME: maylab
    REDIS_SERVER: redis
    REDIS_SERVER_PORT: 6379

# Cache vendor directory
cache:
    paths:
    - vendor/

stages:
    - test
    - build
    - deploy

# Install all dependencies
.install_dependencies: &install_dependencies
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerinit ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-keyscan -H -p 2248 cakehub.sk >> ~/.ssh/known_hosts
    - composer install
    - chmod a+x bin/cake

# PHP Lint script using CakePHP coding standards
.php_lint: &php_lint
    - composer require cakephp/cakephp-codesniffer:dev-master
    - chmod +x vendor/bin/phpcs
    - vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests ./config ./plugins

# CodeCanyon Application Setup
# Remove all unnecessary folders
.clean_folders: &clean_folders
  - rm -rf .git
  - rm -rf ./tmp
  - rm -rf ./logs

# Test section
# Lint
php lint:
    stage: test
    environment:
        name: staging
        url: https://helix.maymeow.tokyo/MayMeowCloudPlatform/maymeow-cloud
    before_script: *install_dependencies
    script: *php_lint
    only:
        # - /^feature\/.*$/
        - develop
    tags:
        - home
        - docker

test cake-service:
    services:
        - mariadb
        - redis
    stage: test
    before_script: *install_dependencies
    script:
        # - bin/cake mcloud_setup
        - phpunit
    tags:
        - home
        - docker

# Build section

build image:
    # image: docker:latest
    # services:
    #    - docker:dind
    stage: build
    before_script: *install_dependencies
    script: *clean_folders
    after_script:
        - export IMAGE_TAG=$(echo -en $CI_COMMIT_REF_NAME | tr -c '[:alnum:]_.-' '-')
        - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
        - docker build --pull -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG" .
        - docker push "$CI_REGISTRY_IMAGE:$IMAGE_TAG"
    tags:
    #    - home
    #    - docker
        - digitalocean
    when: manual
    only:
      - tags

# Deploy Section
# Deploy for CodeCanyon only when tags are set up
deploy_source_code:
    stage: deploy
    environment:
        name: codecanyon
        url: https://codecanyon.net
    before_script:
        - composer selfupdate
        - composer install
        - chmod +x bin/cake
    script: *clean_folders
    only:
        - tags
        - master
    tags:
        - home
        - docker
    artifacts:
        # name: "mcloud-ca-${CI_COMMIT_TAG}-cc"
        paths:
            - .
        expire_in: 2 days

# Digital Ocean
# Backup database before deploy to Digital ocean
backup_db:
    stage: deploy
    script:
        - mkdir _db
        - docker stop maymeowcloud_platform_1
        - docker exec maymeowcloud_db_1 sh -c 'exec mysqldump -u"$MYSQL_USER" -p"$MYSQL_ROOT_PASSWORD" "$MYSQL_DATABASE"' > ./_db/maymeowcloud.sql
    artifacts:
        paths:
            - _db
        expire_in: 7 days
    only:
        - develop
    tags:
        - digitalocean
    when: manual

# Deploy for DigitalOcean
# only for tags
deploy_to_digitalocean:
    stage: deploy
    environment:
        name: digitalocean
        url: http://platform.cakeapp.sk
    before_script:
        - docker -v
        - docker-compose version
    script:
        - docker-compose down -v
        # Pull newest Platform Image
        - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
        - docker pull registry.cakehub.sk/cakesource/platform:develop
        - docker-compose up -d --build
    only:
        - develop
    tags:
        - digitalocean
    when: manual
