version: '2'

services:
    db:
        image: mariadb:10
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: MayMeowCloud2017
            MYSQL_DATABASE: maymeowcloud
            MYSQL_USER: MayMeowCloud2017
            MYSQL_PASSWORD: MayMeowCloud2017

    platform:
        build: .
        depends_on:
            - db
            - redis
        volumes:
            - maymeowcloud_storage_buckets:/var/www/html/webroot/data/storage/buckets
            - maymeowcloud_config:/var/www/html/config
            - /cloud/disks:/var/www/html/webroot/data/storage/disks
            - maymeowcloud_users_data:/var/www/html/webroot/data/users
        #ports:
        #    - "8081:80"
        restart: always
        environment:
            MYSQL_HOST: db
            MYSQL_PORT: 3306
            MYSQL_USER: MayMeowCloud2017
            MYSQL_PASSWORD: MayMeowCloud2017
            MYSQL_DB_NAME: maymeowcloud
            EXTERNAL_URL: http://noted-earth-3754.app.kukolos.eu:8081
            DOCKER_SOCKET: tcp://compute-server:7838
            DEBUG: "true"
            REDIS_SERVER: redis
            REDIS_SERVER_PORT: 6379


    redis:
        build: ./MayMeow/redis
        restart: always

    nginx:
        build: ./MayMeow/lb
        restart: always
        ports:
            - "8081:80"

volumes:
    db_data:
    maymeowcloud_storage_buckets:
    maymeowcloud_config:
    maymeowcloud_users_data:
