<?php
namespace CakeStorage\Controller\Api;

use CakeStorage\Controller\AppController;

/**
 * GitRepositories Controller
 *
 * @property \CakeStorage\Model\Table\GitRepositoriesTable $GitRepositories
 *
 * @method \CakeStorage\Model\Entity\GitRepository[] paginate($object = null, array $settings = [])
 */
class GitRepositoriesController extends AppController
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->loadComponent('RequestHandler');
    }

    public function isAuthorized($user) : bool
    {
        // Allow all users to list, view and add projects
        if (in_array($this->request->getParam('action'), ['projects'])){
            if (isset($user['role']) && $user['role'] === 'user') {
                return true;
            }
        }

        return parent::isAuthorized($user); // TODO: Change the autogenerated stub
    }

    public function projects($id = null)
    {
        if ($this->request->is('json')) {
            $this->set('html', $this->viewBuilder()->build()->cell('CakeStorage.Projects', [$id])->render());
        }
    }
}
