<?php
namespace MCloudCompute\Controller\Api\V1;

use Cake\Event\Event;
use MCloudCompute\Controller\AppController;

/**
 * OutgoingActions Controller
 *
 * @property \MCloudCompute\Model\Table\OutgoingActionsTable $OutgoingActions
 */
class OutgoingActionsController extends AppController
{
    public function initialize()
    {
        parent::initialize();
        $this->loadComponent('RequestHandler');
    }

    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
        $this->Auth->allow(['check']);
    }

    /**
     * @param null $app_key
     * @param null $app_secret
     */
    public function check($app_key = null, $app_secret = null)
    {
        $payload = null;
        $outgoingAction = $this->OutgoingActions->find()
            ->where([
                'app_key LIKE' => $app_key,
                'app_secret LIKE' => $app_secret,
                'status LIKE' => 'waiting'
            ])
            ->first();

        if ($outgoingAction) {
            $payload = json_decode($outgoingAction->payload);

            $outgoingAction->status = 'done';
            $this->OutgoingActions->save($outgoingAction);
        }

        $this->set('payload', $payload);
        $this->set('_serialize', 'payload');
    }
}
