<?php
namespace CakeLogs\Controller\Api;

use Cake\Event\Event;
use CakeAuth\Traits\AuthAppTrait;
use CakeLogs\Controller\AbstractCloudLogsController;
use CakeLogs\Controller\AppController;

/**
 * CloudLogs Controller
 *
 * @property \CakeLogs\Model\Table\CloudLogsTable $CloudLogs
 *
 * @method \CakeLogs\Model\Entity\CloudLog[] paginate($object = null, array $settings = [])
 */
class CloudLogsController extends AbstractCloudLogsController
{
    use AuthAppTrait;

    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub

        $this->Auth->allow(['remoteLog']);
    }

    public function remoteLog()
    {
        if ($this->_getAuthApplication($this->request, $this->response)) {
            return $this->response->withStringBody(json_encode([
                'message' => 'OK',
                'code' => '200'
            ]))->withStatus(200);
        }

        $log = $this->CloudLogs->newEntity();
        $log->resource_key = 'Logger';
        $log->event_type = 'success';
        $log->severity = 'low';
        $log->json_data = $this->request->getBody();

        $this->CloudLogs->save($log);

        return $this->response->withStringBody('OK')->withStatus(200);
    }
}
