<?php

namespace CakeStorage\Controller;

use App\Controller\AppController as BaseController;
use Cake\Event\Event;
use MayMeow\Crud\View\Menu\MenuItem;

class AppController extends BaseController
{
    public function beforeRender(Event $event)
    {
        parent::beforeRender($event); // TODO: Change the autogenerated stub
    }

    protected function _adminMenu()
    {
        return [
            new MenuItem('<i class="fab fa-git"></i> Repositories', ['action' => 'index', 'controller' => 'GitRepositories'], ['escape' => false, 'class' => 'nav-link']),
            new MenuItem('<i class="fab fa-bitbucket"></i> Buckets', ['action' => 'index', 'controller' => 'Buckets'], ['escape' => false, 'class' => 'nav-link']),
        ];
    }
}
