<?php

namespace CakeStorage\Controller;

use App\Controller\AppController as BaseController;
use App\Factories\MenuFactory;
use Cake\Event\Event;

class AppController extends BaseController
{
    public function beforeRender(Event $event)
    {
        parent::beforeRender($event); // TODO: Change the autogenerated stub
    }

    protected function _adminMenu()
    {
        return MenuFactory::storageMenu();
    }
}
