<?php
namespace MCloudHome\Controller\Api\V1;

use Cake\Event\Event;
use CakeAuth\Traits\AuthAppTrait;
use CakeAuth\Traits\AuthTokenTrait;
use MCloudHome\Controller\AbstractDevicesController;

/**
 * Devices Controller
 *
 * @property \MCloudHome\Model\Table\DevicesTable $Devices
 */
class DevicesController extends AbstractDevicesController
{
    use AuthAppTrait, AuthTokenTrait;

    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
        $this->Auth->allow(['index', 'view']);

        //return $this->_authorizeApplication($this->request, $this->response);

        return $this->_authorizeWithToken($this->request, $this->response, $this->_getAuthApplication($this->request, $this->response));
    }
}
