<?php
namespace CakeAuth\Controller\Api\v1;

use Cake\Event\Event;
use CakeAuth\Authenticator\TokenAuthenticator;
use CakeAuth\Controller\AbstractUsersController;
use CakeAuth\Controller\AppController;

/**
 * Users Controller
 *
 * @property \CakeAuth\Model\Table\UsersTable $Users
 *
 * @method \CakeAuth\Model\Entity\User[] paginate($object = null, array $settings = [])
 */
class UsersController extends AbstractUsersController
{

    protected $authenticator;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->authenticator = new TokenAuthenticator();
    }

    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub

        $this->Auth->allow(['index']);

        return $this->authenticator->authenticate($this->request, $this->response);
    }

}
