<?php
namespace CakeAuth\Controller;

use Cake\Event\Event;
use Cake\Filesystem\Folder;
use CakeApp\Shell\Ssh\AuthorizedKeys;
use CakeAuth\Controller\AppController;

/**
 * SshKeys Controller
 *
 * @property \CakeAuth\Model\Table\SshKeysTable $SshKeys
 *
 * @method \CakeAuth\Model\Entity\SshKey[] paginate($object = null, array $settings = [])
 */
class SshKeysController extends AbstractSshKeysController
{
    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub

        $this->set('crud_admin_menu', $this->_adminMenu());
    }

    public function isAuthorized($user) : bool
    {
        // Allow all users to list, view and add projects
        if (in_array($this->request->getParam('action'), ['index', 'add'])){
            if (isset($user['role']) && $user['role'] === 'user') {
                return true;
            }
        }

        if (in_array($this->request->getParam('action'), ['view', 'edit', 'delete'])){
            $id = $this->request->getParam('pass.0');
            if ($this->SshKeys->isOwnedBy($id, $user['id'])) {
                return true;
            }
        }

        return parent::isAuthorized($user); // TODO: Change the autogenerated stub
    }
}
